services:
  - type: web
    name: similar-case-search
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
